export const GET_RANDOM_RECIPE_SUCCESS = 'GET_RANDOM_RECIPE_SUCCESS';
export const GET_RANDOM_RECIPE_ERR = 'GET_RANDOM_RECIPE_ERR';

export const GET_RECIPE_DETAILS_SUCCESS = 'GET_RECIPE_DETAILS_SUCCESS';
export const GET_RECIPE_DETAILS_ERR = 'GET_RECIPE_DETAILS_ERR';

export const GET_RECIPE_OPTIONS_SUCCESS = 'GET_RECIPE_OPTIONS_SUCCESS';
export const GET_RECIPE_OPTIONS_ERR = 'GET_RECIPE_OPTIONS_ERR';
export const GET_SIMILAR_RECIPE_SUCCESS = 'GET_SIMILAR_RECIPE_SUCCESS';
export const GET_SIMILAR_RECIPE_ERR = 'GET_SIMILAR_RECIPE_ERR';

export const RECIPE_QUERY = 'RECIPE_QUERY';
export const BUTTON_DISPLAY = 'BUTTON_DISPLAY';
export const SELECT_TEXT = 'SELECT_TEXT';

export const ADD_SCORE = 'ADD_SCORE';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const QUIZ_RESET = 'QUIZ_RESET';
export const QUIZ_SETUP = 'QUIZ_SETUP';
export const INCORRECT = 'INCORRECT';
